"""Added auth_tokens field to User

Revision ID: 04e08ac9b53e
Revises: fa302e3f7c74
Create Date: 2025-11-13 17:57:37.091263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e08ac9b53e'
down_revision: Union[str, Sequence[str], None] = 'fa302e3f7c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_refresh_token'), 'auth', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_refresh_token'), table_name='auth')
    # ### end Alembic commands ###
